controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz

    arm_controller:
      type: "forward_command_controller/ForwardCommandController"

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gripper_controller:
      type: forward_command_controller/ForwardCommandController

arm_controller:
  ros__parameters:
    joints:
      - link_1_to_link_2
      - link_2_to_link_3
      - link_3_to_link_4

    interface_name: effort

    open_loop_control: true
    allow_integration_in_goal_trajectories: true

gripper_controller:
  ros__parameters:
    joints:
      - link_4_to_gripper

    interface_name: effort

    open_loop_control: true
    allow_integration_in_goal_trajectories: true