<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="vertical_3dof_robot">

  <!-- Constants -->
  <xacro:property name="link_radius" value="0.01"/>
  <xacro:property name="link_length" value="0.1"/>

  <xacro:property name="m1" value="1.0"/>
  <xacro:property name="m2" value="0.8"/>
  <xacro:property name="m3" value="0.6"/>
  <xacro:property name="m4" value="0.5"/>

  <!-- Inertia Macro for Z-Extended Boxes -->
  <xacro:macro name="inertial_box_z" params="mass x y z">
    <inertial>
      <origin xyz="0 0 ${z/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia 
        ixx="${(1/12.0)*mass*(y*y + z*z)}"
        iyy="${(1/12.0)*mass*(x*x + z*z)}"
        izz="${(1/12.0)*mass*(x*x + y*y)}"
        ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </xacro:macro>

  <!-- Link Macro (Z-Axis Extension) -->
  <xacro:macro name="z_link" params="name mass color">
    <link name="${name}">
      <xacro:inertial_box_z mass="${mass}" x="${link_radius*2}" y="${link_radius*2}" z="${link_length}"/>
      <visual>
        <origin xyz="0 0 ${link_length/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${link_radius*2} ${link_radius*2} ${link_length}"/>
        </geometry>
        <material><color rgba="${color}"/></material>
      </visual>
      <collision>
        <origin xyz="0 0 ${link_length/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${link_radius*2} ${link_radius*2} ${link_length}"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <!-- World -->
  <link name="world"/>
  <xacro:z_link name="link_1" mass="${m1}" color="0.6 0.6 0.6 1.0"/>
  <joint name="world_to_link_1" type="fixed">
    <parent link="world"/>
    <child link="link_1"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Link 2 -->
  <xacro:z_link name="link_2" mass="${m2}" color="0.9 0.0 0.0 1.0"/>
  <joint name="link_1_to_link_2" type="revolute">
    <parent link="link_1"/>
    <child link="link_2"/>
    <origin xyz="0 0 ${link_length}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.57" upper="1.57" effort="50" velocity="1.0"/>
  </joint>

  <!-- Link 3 -->
  <xacro:z_link name="link_3" mass="${m3}" color="0.0 0.7 1.0 1.0"/>
  <joint name="link_2_to_link_3" type="revolute">
    <parent link="link_2"/>
    <child link="link_3"/>
    <origin xyz="0 0 ${link_length}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.57" upper="1.57" effort="50" velocity="1.0"/>
  </joint>

  <!-- Link 4 -->
  <xacro:z_link name="link_4" mass="${m4}" color="0.0 0.8 0.3 1.0"/>
  <joint name="link_3_to_link_4" type="revolute">
    <parent link="link_3"/>
    <child link="link_4"/>
    <origin xyz="0 0 ${link_length}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.57" upper="1.57" effort="50" velocity="1.0"/>
  </joint>

  <!-- Gripper -->
  <link name="gripper_base">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.05"/>
      <inertia ixx="1e-5" iyy="1e-5" izz="1e-5" ixy="0" ixz="0" iyz="0"/>
    </inertial>

    <!-- Left Finger -->
    <visual>
      <origin xyz="0.015 0 ${0.02}" rpy="0 0 0"/>
      <geometry><box size="0.01 0.01 0.05"/></geometry>
    </visual>

    <!-- Right Finger -->
    <visual>
      <origin xyz="-0.015 0 ${0.02}" rpy="0 0 0"/>
      <geometry><box size="0.01 0.01 0.05"/></geometry>
    </visual>
  </link>

  <joint name="link_4_to_gripper" type="fixed">
    <parent link="link_4"/>
    <child link="gripper_base"/>
    <origin xyz="0 0 ${link_length}" rpy="0 0 0"/>
  </joint>

</robot>
