<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="cylindrical_3dof_robot">

  <!-- Link Parameters -->
   <!-- changes the dimentions -->
  <xacro:property name="r1" value="0.01"/>
  <xacro:property name="r2" value="0.01"/>
  <xacro:property name="r3" value="0.01"/>
  <xacro:property name="r4" value="0.01"/>

  <xacro:property name="l1" value="0.1"/>
  <xacro:property name="l2" value="0.1"/>
  <xacro:property name="l3" value="0.1"/>
  <xacro:property name="l4" value="0.1"/>

  <xacro:property name="m1" value="1.0"/>
  <xacro:property name="m2" value="0.8"/>
  <xacro:property name="m3" value="0.6"/>
  <xacro:property name="m4" value="0.5"/>

  <!-- Inertia macro for solid cylinder along Z-axis -->
  <xacro:macro name="inertial_cylinder_z" params="mass radius length">
    <inertial>
      <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${(1/12.0)*mass*(3*radius*radius + length*length)}"
        iyy="${(1/12.0)*mass*(3*radius*radius + length*length)}"
        izz="${0.5*mass*radius*radius}"
        ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </xacro:macro>

  <!-- Cylindrical Link Macro -->
  <xacro:macro name="cylinder_link" params="name mass radius length color">
    <link name="${name}">
      <xacro:inertial_cylinder_z mass="${mass}" radius="${radius}" length="${length}"/>
      <visual>
        <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${radius}" length="${length}"/>
        </geometry>
        <material><color rgba="${color}"/></material>
      </visual>
      <collision>
        <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${radius}" length="${length}"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <!-- World and Link 1 (Fixed) -->
  <link name="world"/>
  <xacro:cylinder_link name="link_1" mass="${m1}" radius="${r1}" length="${l1}" color="0.6 0.6 0.6 1.0"/>
  <joint name="world_to_link_1" type="fixed">
    <parent link="world"/>
    <child link="link_1"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Link 2 -->
  <xacro:cylinder_link name="link_2" mass="${m2}" radius="${r2}" length="${l2}" color="1.0 0.0 0.0 1.0"/>
  <joint name="link_1_to_link_2" type="revolute">
    <parent link="link_1"/>
    <child link="link_2"/>
    <origin xyz="0 0 ${l1}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.57" upper="1.57" effort="50" velocity="1.0"/>
  </joint>

  <!-- Link 3 -->
  <xacro:cylinder_link name="link_3" mass="${m3}" radius="${r3}" length="${l3}" color="0.0 0.7 1.0 1.0"/>
  <joint name="link_2_to_link_3" type="revolute">
    <parent link="link_2"/>
    <child link="link_3"/>
    <origin xyz="0 0 ${l2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.57" upper="1.57" effort="50" velocity="1.0"/>
  </joint>

  <!-- Link 4 -->
  <xacro:cylinder_link name="link_4" mass="${m4}" radius="${r4}" length="${l4}" color="0.0 0.8 0.3 1.0"/>
  <joint name="link_3_to_link_4" type="revolute">
    <parent link="link_3"/>
    <child link="link_4"/>
    <origin xyz="0 0 ${l3}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.57" upper="1.57" effort="50" velocity="1.0"/>
  </joint>

  <!-- Gripper: Two Fingers Only -->
  <link name="gripper_base">

    <!-- Left Finger -->
    <visual>
      <origin xyz="0.015 0 0.025" rpy="0 0 0"/>
      <geometry><box size="0.01 0.01 0.05"/></geometry>
      <material><color rgba="0.2 0.2 0.2 1.0"/></material>
    </visual>
    <collision>
      <origin xyz="0.015 0 0.025" rpy="0 0 0"/>
      <geometry><box size="0.01 0.01 0.05"/></geometry>
    </collision>

    <inertial>
      <origin xyz="0.015 0 0.025" rpy="0 0 0"/>
      <mass value="0.025"/>
      <inertia ixx="1e-5" iyy="1e-5" izz="1e-5" ixy="0" ixz="0" iyz="0"/>
    </inertial>

    <!-- Right Finger -->
    <visual>
      <origin xyz="-0.015 0 0.025" rpy="0 0 0"/>
      <geometry><box size="0.01 0.01 0.05"/></geometry>
    </visual>
    <collision>
      <origin xyz="-0.015 0 0.025" rpy="0 0 0"/>
      <geometry><box size="0.01 0.01 0.05"/></geometry>
    </collision>

    <inertial>
      <origin xyz="-0.015 0 0.025" rpy="0 0 0"/>
      <mass value="0.025"/>
      <inertia ixx="1e-5" iyy="1e-5" izz="1e-5" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="link_4_to_gripper" type="fixed">
    <parent link="link_4"/>
    <child link="gripper_base"/>
    <origin xyz="0 0 ${l4}" rpy="0 0 0"/>
  </joint>

</robot>
